### ISSUE TITLE
Wrong WiFi firmware config for imx6ul-var-dart ?

### ISSUE THREAD

**Issue by floion** [varigit/meta-variscite-fsl-community#17] opened 2019-02-13 16:15 UTC
Hi, I am using meta-variscite-fslc at the `sumo` version for the imx6ul-var-dart board.
On this board the WiFi does not work. I see the following in dmesg:

> usbcore: registered new interface driver brcmfmac
mmc0: new high speed SDIO card at address 0001
brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
usbcore: deregistering interface driver brcmfmac
mmc0: card 0001 removed

The above is tried 3 times, as per https://github.com/varigit/meta-variscite-fslc/blob/sumo/recipes-connectivity/bcm43xx-utils/bcm43xx-utils/variscite-wifi#L54 and then gives up and no wireless interface is brought up.

However, I have switched the wifi firmware config with brcmfmac43430-sdio.txt.ap6210 from https://wolk.wopwop.cc/s/AmPFsOgJdnK4xMU?path=%2Fbrcm-firmware (copied it to the rootfs under the name `/lib/firmware/brcm/brcmfmac43430-sdio.txt`) . Upon reboot, I see in dmesg:

> [   31.321594] usbcore: registered new interface driver brcmfmac
[   31.537836] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Sep 13 2017 15:43:06 version 7.45.41.47 (r668030 CY) FWID 01-2a53ca47
[   31.719464] brcmfmac: brcmf_cfg80211_reg_notifier: not a ISO3166 code (0x30 0x30)

and the wlan0 interface is up. So a step forward. However, iwconfig reports no wireless extension on wlan0 and wpa_supplicant in stuck in a scan loop. This is indication that still this is not the correct wifi firmware config but still is better than the original.

Is the WiFi working for you guys for the imx6ul-var-dart?
Is there a newer firmware blob and firmware config for the wifi chipset present in the imx6ul-var-dart board?
Thanks

**Comment by eranmati** [comment] 2019-02-13 16:37
Hi Florin.
Of course Wi-Fi is working.

Please see:
http://variwiki.com/

If you have an issue, please open a ticket in the Variscite customer portal:
https://www.variscite.com/support/variscite-customer-portal

Regards,
Eran

**Comment by floion** [comment] 2019-02-13 19:54
Hi @eranmati I think we have a ticket opened there as well, but just for completeness, here are some reports from other people on the same issue:

http://forum.variscite.com/viewtopic.php?t=427

and 

https://github.com/balena-os/balena-os/issues/292

**Comment by eranmati** [comment] 2019-02-17 10:48
The issue reported on our forum was caused by the customer's own carrier board design.
We don't have such issue reports on our own carrier board.

You can test our Sumo recovery SD card and verify that it works.
I guess the issue is coming from the integration to  balena-OS.

I'm closing this issue now. Please continue this on the Variscite customer portal, and we'll try to help.

**Closed as completed by eranmati** 2019-02-17 10:48 UTC
